apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste-pod
  name: teste-pod
spec:
  containers:
  - image: nginx:1.22.1
    name: teste-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
